from src.infrastructure.adapters.pyautogui_mouse_adapter import PyautoguiMouseAdapter
from src.infrastructure.adapters.pynput_mouse_loop_breaker_adapter import PynputMouseLoopBreakerAdapter
from src.infrastructure.adapters.pynput_click_recorder.pynput_click_recorder_adapter import PynputClickRecorderAdapter
